[functions]
external_node_modules = ["axios", "mongodb"]

[build]
  command = "npm run build && npm run prerender"
  functions = "netlify/functions"
  publish = "dist/schlosswochen-ch/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
  cache-control = '''
  max-age=0,
  no-cache,
  no-store,
  must-revalidate'''
